services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: mercafacil_adm
      POSTGRES_PASSWORD: testemercafacil
      POSTGRES_DB: mercafacil
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mercafacil_adm -d mercafacil"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: mercafacil_adm
      POSTGRES_PASSWORD: testemercafacil
      POSTGRES_DB: mercafacil
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    volumes:
      - ./data:/app/data:ro #ro pra readonly